% Author: Ali Karimi <ali.karimi@brain.mpg.de>
util.clearAll;
% Get the apicalTuft location
apTuft=apicalTuft('PPC2WeirdV1_l2vsl3vsl5');
l1piaGrid=skeleton(fullfile...
    (util.dir.getAnnotation,'l2vsl3vsl5','L1PiaGrid'));

%% Plot apical dendritic trees
trIndices{1}=apTuft.getTreeWithName(...
    'layer5ApicalDendrite_dist2soma',...
    'first');
trIndices{2}=apTuft.getTreeWithName(...
    'layer3ApicalDendrite_dist2soma',...
    'first');
colors={l5color,l3color};
for g=1:2
    dendrite.l2vsl3vsl5.saveGallery_PPC2(apTuft,trIndices{g},...
        colors{g});
end