function [out]=nmlName()
% returns the names of the nml files from different tracing types
% Author: Ali Karimi <ali.karimi@brain.mpg.de>
out.bifurcation={'S1_bifurcation','V2_bifurcation',...
    'PPC_bifurcation','ACC_bifurcation'};
out.apicalDiameter={'S1_apicalDiameter','V2_apicalDiameter',...
    'PPC_apicalDiameter','ACC_apicalDiameter'};
out.dist2Soma={'S1_dist2Soma','V2_dist2Soma',...
    'PPC_dist2Soma','ACC_dist2Soma'};
out.inhibitoryAxon={'S1_inhibitoryAxon','V2_inhibitoryAxon',...
    'PPC_inhibitoryAxon','ACC_inhibitoryAxon'};
out.spineRatioMappingL1={'LPtAExcitatory_spineRatioMappingL1',...
    'LPtAInhibitory_spineRatioMappingL1'};
out.spineRatioMappingL2={'V2_spineRatioMappingL2','PPC_spineRatioMappingL2',...
    'ACC_spineRatioMappingL2'};
out.wholeApical={'S1_wholeApical','V2_wholeApical','PPC_wholeApical',...
    'ACC_wholeApical'};
out.l2vsl3vsl5={'PPC2_l2vsl3vsl5','LPtA_l2vsl3vsl5'};
end
