function [newComments] = getNewComments()
%GETNEWCOMMENTS 
newComments{4}={'shaftOfL2ApicalDendrite','shaftOfDeepApicalDendrite',...
    'layer2CellBody','shaftOfOtherDendrite',...
    'spineOfL2ApicalDendrite_DoubleInnervated'...
    'spineOfL2ApicalDendrite_neck',...
    'spineOfL2ApicalDendrite_singleInnervated'...
    'spineOfDeepApicalDendrite_DoubleInnervated',...
    'spineOfDeepApicalDendrite_neck',...
    'spineOfDeepApicalDendrite_singleInnervated',...
    'spineOfOtherDendrite_DoubleInnervated','unsure Synapse'...
    'spineOfOtherDendrite_neck','unsure Synapse'...
    'spineOfOtherlDendrite_singleInnervated','unsureSynapse'...
    'axonInitialSegment','Glia'};
newComments{3}={'shaftOfL2ApicalDendrite',...
    'shaftOfDeepApicalDendrite',...
    'layer2CellBody','shaftOfOtherDendrite',...
    'spineOfL2ApicalDendrite_DoubleInnervated'...
    'spineOfL2ApicalDendrite_neck',...
    'spineOfL2ApicalDendrite_singleInnervated'...
    'spineOfDeepApicalDendrite_DoubleInnervated',...
    'spineOfDeepApicalDendrite_neck',...
    'spineOfDeepApicalDendrite_singleInnervated',...
    'spineOfOtherDendrite_DoubleInnervated','unsure Synapse'...
    'spineOfOtherDendrite_neck','unsure Synapse'...
    'spineOfOtherlDendrite_singleInnervated','unsure Synapse'...
    'axonInitialSegment','Glia'};
newComments{2}={'shaftOfL2ApicalDendrite','shaftOfDeepApicalDendrite',...
    'layer2CellBody','shaftOfOtherDendrite',...
    'spineOfL2ApicalDendrite_DoubleInnervated'...
    'spineOfL2ApicalDendrite_neck',...
    'spineOfL2ApicalDendrite_singleInnervated'...
    'spineOfDeepApicalDendrite_DoubleInnervated',...
    'spineOfDeepApicalDendrite_neck',...
    'spineOfDeepApicalDendrite_singleInnervated',...
    'spineOfOtherDendrite_DoubleInnervated','unsure Synapse'...
    'spineOfOtherDendrite_neck','unsure Synapse'...
    'spineOfOtherlDendrite_singleInnervated','unsure Synapse'...
    'axonInitialSegment','Glia'};
newComments{1}={'shaftOfL2ApicalDendrite','shaftOfDeepApicalDendrite',...
    'layer2CellBody','shaftOfOtherDendrite',...
    'spineOfL2ApicalDendrite_DoubleInnervated'...
    'spineOfL2ApicalDendrite_neck',...
    'spineOfL2ApicalDendrite_singleInnervated'...
    'spineOfDeepApicalDendrite_DoubleInnervated',...
    'spineOfDeepApicalDendrite_neck',...
    'spineOfDeepApicalDendrite_singleInnervated',...
    'spineOfOtherDendrite_DoubleInnervated','unsure Synapse'...
    'spineOfOtherDendrite_neck','unsure Synapse'...
    'spineOfOtherlDendrite_singleInnervated','unsure Synapse'...
    'axonInitialSegment','Glia'};

end

